// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721005340_AddMoreQuizQuestions")]
    partial class AddMoreQuizQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("backend.Models.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectOption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QuizQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectOption = "B",
                            OptionA = "Oxygen",
                            OptionB = "Carbon dioxide",
                            OptionC = "Nitrogen",
                            OptionD = "Helium",
                            QuestionText = "What is the main greenhouse gas released by burning fossil fuels?"
                        },
                        new
                        {
                            Id = 2,
                            CorrectOption = "C",
                            OptionA = "Coal",
                            OptionB = "Natural gas",
                            OptionC = "Solar power",
                            OptionD = "Petroleum",
                            QuestionText = "Which of these is a renewable energy source?"
                        },
                        new
                        {
                            Id = 3,
                            CorrectOption = "B",
                            OptionA = "Noise pollution only",
                            OptionB = "Carbon emissions",
                            OptionC = "Water pollution",
                            OptionD = "Light pollution",
                            QuestionText = "Walking or cycling instead of driving mainly reduces which type of pollution?"
                        },
                        new
                        {
                            Id = 4,
                            CorrectOption = "B",
                            OptionA = "The number of trees you've planted",
                            OptionB = "The total greenhouse gases produced by your activities",
                            OptionC = "The distance you've walked",
                            OptionD = "The amount of recycling you do",
                            QuestionText = "What does 'carbon footprint' measure?"
                        },
                        new
                        {
                            Id = 5,
                            CorrectOption = "B",
                            OptionA = "Using single-use bottles",
                            OptionB = "Using a reusable bottle or cup",
                            OptionC = "Buying more plastic bags",
                            OptionD = "Leaving the tap running",
                            QuestionText = "Which everyday habit helps reduce plastic waste the most?"
                        },
                        new
                        {
                            Id = 6,
                            CorrectOption = "B",
                            OptionA = "Cities are cooler than rural areas",
                            OptionB = "Cities are warmer than surrounding rural areas due to human activity",
                            OptionC = "Islands are heating up faster than cities",
                            OptionD = "A type of ocean current",
                            QuestionText = "Which of these best describes 'urban heat island' effect?"
                        },
                        new
                        {
                            Id = 7,
                            CorrectOption = "A",
                            OptionA = "Walking",
                            OptionB = "Driving alone",
                            OptionC = "Flying",
                            OptionD = "Cruise ship",
                            QuestionText = "Which mode of transport typically produces the least CO2 per passenger?"
                        },
                        new
                        {
                            Id = 8,
                            CorrectOption = "B",
                            OptionA = "They release oxygen only at night",
                            OptionB = "They absorb carbon dioxide from the atmosphere",
                            OptionC = "They increase soil erosion",
                            OptionD = "They raise local temperatures",
                            QuestionText = "What is the main benefit of planting trees for the climate?"
                        },
                        new
                        {
                            Id = 9,
                            CorrectOption = "A",
                            OptionA = "Taking shorter showers",
                            OptionB = "Leaving the tap running while brushing teeth",
                            OptionC = "Washing a half-empty dishwasher load",
                            OptionD = "Watering the garden at midday",
                            QuestionText = "Which of these actions saves the most water at home?"
                        },
                        new
                        {
                            Id = 10,
                            CorrectOption = "B",
                            OptionA = "Energy that runs out permanently once used",
                            OptionB = "Energy from sources that naturally replenish, like sun or wind",
                            OptionC = "Energy only generated by burning coal",
                            OptionD = "Energy stored exclusively in batteries",
                            QuestionText = "What does 'renewable energy' mean?"
                        });
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActiveDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastQuizDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("backend.Models.WalkingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("EarnedPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Steps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WalkingRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
