using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace backend.Migrations
{
    /// <inheritdoc />
    public partial class AddMoreQuizQuestions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "QuizQuestions",
                columns: new[] { "Id", "CorrectOption", "OptionA", "OptionB", "OptionC", "OptionD", "QuestionText" },
                values: new object[,]
                {
                    { 7, "A", "Walking", "Driving alone", "Flying", "Cruise ship", "Which mode of transport typically produces the least CO2 per passenger?" },
                    { 8, "B", "They release oxygen only at night", "They absorb carbon dioxide from the atmosphere", "They increase soil erosion", "They raise local temperatures", "What is the main benefit of planting trees for the climate?" },
                    { 9, "A", "Taking shorter showers", "Leaving the tap running while brushing teeth", "Washing a half-empty dishwasher load", "Watering the garden at midday", "Which of these actions saves the most water at home?" },
                    { 10, "B", "Energy that runs out permanently once used", "Energy from sources that naturally replenish, like sun or wind", "Energy only generated by burning coal", "Energy stored exclusively in batteries", "What does 'renewable energy' mean?" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "QuizQuestions",
                keyColumn: "Id",
                keyValue: 7);

            migrationBuilder.DeleteData(
                table: "QuizQuestions",
                keyColumn: "Id",
                keyValue: 8);

            migrationBuilder.DeleteData(
                table: "QuizQuestions",
                keyColumn: "Id",
                keyValue: 9);

            migrationBuilder.DeleteData(
                table: "QuizQuestions",
                keyColumn: "Id",
                keyValue: 10);
        }
    }
}
